SELECT AVG(total_revenue) AS avg_revenue_per_customer
FROM (
    SELECT customer_id, SUM(amount) AS total_revenue
    FROM Transactions
    GROUP BY customer_id
);
SELECT SUM(amount)/count(amount) as avg from transactions;
SELECT customer_id,SUM(amount) as avg from transactions group by customer_id;

#Find the total number of tickets sold for each ride:
SELECT r.ride_name, COUNT(ti.ticket_id) as total_tickets
FROM ride r
LEFT JOIN ticket ti ON r.ride_id = ti.ride_id
GROUP BY r.ride_id
ORDER BY total_tickets DESC;

#Find the total sales for each restaurant type:
SELECT r.restaurant_type, SUM(t.amount) as total_sales
FROM restaurant r
LEFT JOIN transactions t ON r.restaurant_id = t.restaurant_id
GROUP BY r.restaurant_type
ORDER BY total_sales DESC;

#Get the list of customers who have visited a specific ride:
SELECT c.first_name, c.last_name, r.ride_name
FROM customer c
LEFT JOIN ticket ti ON c.customer_id = ti.customer_id
LEFT JOIN ride r ON ti.ride_id = r.ride_id
WHERE r.ride_name = 'Roller Coaster';

#how wany tickets sold of each ride
SELECT r.restaurant_type, SUM(t.amount) AS total_sales
FROM transactions t
LEFT JOIN restaurant r ON t.restaurant_id = r.restaurant_id
WHERE t.restaurant_id IS NOT NULL
GROUP BY r.restaurant_type;


#Find the total sales for each product category in the shops:
SELECT s.products, SUM(t.amount) as total_sales
FROM shop s
LEFT JOIN transactions t ON s.shop_id = t.shop_id
GROUP BY s.products
ORDER BY total_sales DESC;

#Get the list of rides with the longest duration:
SELECT ride_name, ride_duration
FROM ride
ORDER BY ride_duration DESC
LIMIT 10;

#Get the most popular restaurant:
SELECT restaurant_name, COUNT(*) as total_sales FROM Transactions
JOIN Restaurant ON Transactions.restaurant_id = Restaurant.restaurant_id
GROUP BY restaurant_name
ORDER BY total_sales DESC
LIMIT 1;

#Find the top customers by total spending, along with the total number of tickets and the total number of rides they have been on.
SELECT C.first_name, C.last_name, COUNT(DISTINCT T.ticket_id) as num_tickets, COUNT(DISTINCT T.ride_id) as num_rides, SUM(Tr.amount) as total_spending
FROM Customer C
INNER JOIN Ticket T ON C.customer_id = T.customer_id
INNER JOIN Transactions Tr ON C.customer_id = Tr.customer_id
GROUP BY C.customer_id
ORDER BY total_spending DESC
LIMIT 1;

#Get the average ride duration:
SELECT AVG(ride_duration) as average_duration FROM Ride;

#Contact info of Customers
SELECT customer_email ,customer_phone_number FROM Customer;

#Find the total revenue generated by each restaurant.
SELECT r.restaurant_name, SUM(t.amount) AS total_revenue
FROM Restaurant r
LEFT JOIN Transactions t ON r.restaurant_id = t.restaurant_id
GROUP BY r.restaurant_name;

#Find the total salary paid to employees in each restaurant.
SELECT Restaurant.restaurant_name, SUM(Employee.employee_salary) AS total_salary_paid
FROM Restaurant
JOIN Employee ON Restaurant.restaurant_id = Employee.restaurant_id
GROUP BY Restaurant.restaurant_name;

#Find the total revenue generated by each restaurant.
SELECT Restaurant.restaurant_name, SUM(Transactions.amount) AS total_revenue
FROM Restaurant
JOIN Transactions ON Restaurant.restaurant_id = Transactions.restaurant_id
GROUP BY Restaurant.restaurant_name;

#Find the total revenue generated by each shop
SELECT Shop.shop_name, SUM(Transactions.amount) AS total_revenue
FROM Shop
JOIN Transactions ON Shop.shop_id = Transactions.shop_id
GROUP BY Shop.shop_name;

#Find the top 5 busiest days (i.e., days with the highest number of tickets sold).
SELECT purchase_date, COUNT(ticket_id) AS ticket_sales
FROM Ticket
GROUP BY purchase_date
ORDER BY ticket_sales DESC
LIMIT 5;
